<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Galaxy.Core\Galaxy.Core.csproj" />
    <ProjectReference Include="..\Galaxy.Data\Galaxy.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
  </ItemGroup>

</Project>
